#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BLANK_IMG_WIDTH 800
#define BLANK_IMG_HEIGHT 600

#define WIDTH_STEP 10
#define HEIGHT_STEP 10

#define MIN_ANGLE (-180)
#define MAX_ANGLE 180
#define ANGLE_STEP 10

#define VEC_SIZE ((BLANK_IMG_WIDTH / WIDTH_STEP) * (BLANK_IMG_HEIGHT / HEIGHT_STEP))

#define TEST_SAMPLES_COUNT 1
#define TRAIN_SAMPLES_COUNT 100

#define CLASSES_MAX_COUNT 10

#define MAX_CLASS_NAME_LENGTH 10

#define MAX_STRING 100

#endif // CONSTANTS_H
